# Generated by Django 3.0.7 on 2021-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210621_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
